# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b24fee0b3df46e90cf16966db2e9278192974223bfd39018d5d131cd5f66f9f482ac9d08b2561f890c1552c3431772ef618b29ff0c44d44e594759e267fe70

test:
  secret_key_base: a4dcb9987aad8a7ebc9c4a93626642d69eb9a2014d479fd43a12dac94541089490361ec022f7264782692f754f84ef4132063eac792ddedef861b8e8c5dd825f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
